language: android
dist: trusty
android:
    components:
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-29.0.0

        # The SDK version used to compile your project
        - android-29


script:
- chmod +x ./gradlew clean test build

branches:
        only:
                - master

